### ISSUE TITLE
Port to LUNA board

### ISSUE THREAD

**Issue by icb-** [hansfbaier/adat-usb2-audio-interface#13]
Would it be possible to port this to the [LUNA board](https://www.crowdsupply.com/great-scott-gadgets/luna)?

The 8 in and out optical ports should fit comfortably on one of the two available PMOD connectors (though power draw may become an issue), and the two DACs on the other.

**Comment by hansfbaier** [comment]
Yes I think that should be entirely possible.
I already ported the design to an ECP5 based board (colorlight i5/i9).
But the ADAT transmitter doesn't work there yet. Once that bug is fixed
there would be no problem.

Best regards,
Hans

**Comment by hansfbaier** [comment]
I think this question has been sufficiently answered. Closing this issue.
