### ISSUE TITLE
Files for assembly?

### ISSUE THREAD

**Issue by JomerDev** [hansfbaier/adat-usb2-audio-interface#16]
Hello, I am very interested in this project and am planning on ordering some from jlcpcb.
However, when I take the files generated in the jlcpcb/gerber folder and upload them it looks like no part is marked for assembly?
Even if I enable assembly on jlcpcb it looks like nothing changes.
I haven't ordered parts with assembly before so there is a high chance I'm just missing something, still, could I get some pointers on how to order the board?

**Comment by hansfbaier** [comment]
You need to upload the bom and cpl files

**Comment by JomerDev** [comment]
🤦‍♂️ I am an idiot. I'm so used to the "Save to cart" button being there that I didn't even realize that I need to go to the next page to upload the assembly files and instead kept looking for a way to upload them on the first page.
Thank you!
