### ISSUE TITLE
USB interface

### ISSUE THREAD

**Issue by danielkucera** [hansfbaier/adat-usb2-audio-interface#5]
Hello,
I like this project and would like to reproduce it with qmtech spartan 6 board.
Can I use USB3300 for USB interface or is there some special feature of 3320 being used?

If so, don't you happen to have one extra unpopulated PCB to sell?

Thank you.

**Comment by hansfbaier** [comment]
The USB3300 cannot be clocked by the FPGA, it needs its own clock, so we really need the USB3320

**Comment by danielkucera** [comment]
Thank you, and what about the PCB to sell?

**Comment by hansfbaier** [comment]
@danielkucera  I edited the post above, please read...

**Comment by danielkucera** [comment]
Okay, I'll try that first. Thanks.

**Comment by hansfbaier** [comment]
Also, I don't have a platform file for the Spartan 6 boards here: 
https://github.com/amaranth-community-unofficial/amaranth-boards
You would have to write one.

**Comment by danielkucera** [comment]
I stuck on this error:
```
ERROR:HDLCompiler:1654 - "/tmp/tmp4pxd9uc8/top.v" Line 13503: Instantiating <audiopll> from unknown module <ALTPLL>
Module car remains a blackbox, due to errors in its contents
```
and then I realized porting to Xilinx would require whole clock generation rewrite:
https://github.com/hansfbaier/adat-usb2-audio-interface/blob/main/gateware/car.py#L49

So putting this on hold indefinitely.

But I wonder if there is a way in amaranth to write a portable code to generate clocks...

**Comment by hansfbaier** [comment]
No amaranth does not provide that.
The PLLs of each FPGA are quite different. Even Cyclone V is not compatible with Cyclone IV.
Try building with --keep
To examine the build
.
ALTPLL is for Intel FPGAs, that won't work with Xilinx

**Comment by fritzbauer** [comment]
There is an open issue to allow for portable clocks in amaranth: https://github.com/amaranth-lang/amaranth/issues/425

**Comment by danielkucera** [comment]
You mean like this?
```
python3 adat_usb2_audio_interface.py --keep
```

The result is the same.

**Comment by hansfbaier** [comment]
Yes, but then you can look into the log files to find out about why it
failed
