### ISSUE TITLE
S/PDIF support?

### ISSUE THREAD

**Issue by nikitalita** [hansfbaier/adat-usb2-audio-interface#7]
I realize that S/PDIF is a different protocol and may take some effort to work because of variable clock speeds, but is this something that you are thinking about implementing in the future?

**Comment by hansfbaier** [comment]
Yes, I have been thinking about it, but it's not a priority at the moment.

**Comment by nikitalita** [comment]
I may do just that. Is the current board revision tested and working? Might order it off of JLCPCB.

**Comment by nikitalita** [comment]
Also, I note that the board that you have in the picture with the 5CEFA2F23 is no longer in stock or manufactured: https://www.aliexpress.com/item/2252799820307397.html

There's another board with an 5CEFA5F23 and more SRAM available; will this work?
https://www.aliexpress.com/item/3256801596388647.html

**Comment by hansfbaier** [comment]
I actually don't recommend the Cyclone V, any Cyclone IV board from QMTech is actually better.

**Comment by hansfbaier** [comment]
This will be the best value for money, hands down: https://www.aliexpress.com/item/1005004065727282.html
I already have that board, but I still need to write a board support file for that.
I actually developed most of the current code with this board: https://www.aliexpress.com/item/32949281189.html

**Comment by nikitalita** [comment]
> This will be the best value for money, hands down: https://www.aliexpress.com/item/1005004065727282.html I already have that board, but I still need to write a board support file for that. I actually developed most of the current code with this board: https://www.aliexpress.com/item/32949281189.html

Ok, I will get the first one.

Are there any special requirements for ordering the PCB off of JLCPCB? For example, is this a fixed-impedance board?

**Comment by hansfbaier** [comment]
No it isn't.
Four layer board with standard settings.

**Comment by rusk911** [comment]
> This will be the best value for money, hands down: https://www.aliexpress.com/item/1005004065727282.html I already have that board, but I still need to write a board support file for that. I actually developed most of the current code with this board: https://www.aliexpress.com/item/32949281189.html

Hello. Is the current PCB and code still compatibile with EP4CE15 board you mentioned? Or may be smaller? EP4CE6? Can you please add some brief board requirements to readme?

**Comment by hansfbaier** [comment]
@rusk911 EP4CE6 is too small, the EP4CE15 will fit
