### ISSUE TITLE
Board exceeds JLCPCB capabilities

### ISSUE THREAD

**Issue by nikitalita** [hansfbaier/adat-usb2-audio-interface#9]
Got this message from JLCPCB and they cancelled my order:

"After marking the hole compensation of the original 0.4/0.6 mm, the minimum hole distance is only about 0.17 mm, and the minimum hole distance line is only about 0.08, which exceeds our capabilities. (the minimum hole distance of different networks must be greater than 0.33 mm , the hole distance line must be greater than 0.23 mm)"

I did notice that the visa and tracks were awfully close to each other, but i figured you had submitted this to JLCPCB before so i didn’t think it was an issue.

I’d do this myself, but modifying this design to fix this issue messes with it far more than I am comfortable with.

the full list of capabilities can be found here: https://jlcpcb.com/capabilities/Capabilities

**Comment by hansfbaier** [comment]
Did they send a picture with an example?
I got something like this in the past, it looks I will have to update some of  the design rules.

**Comment by nikitalita** [comment]
Not that I can see; I’ll ask support if they have them

**Comment by hansfbaier** [comment]
@nikitalita I pushed a new version, with bigger hole-to-hole clearance. Try that one again.

**Comment by nikitalita** [comment]
Did you mean to get rid of the ground plane on F.Cu?

**Comment by nikitalita** [comment]
also, I'm still noticing some spacing issues with copper to hole, despite the board setup having the correct constraints, I'm not sure why ERC is not picking this up:
![image](https://user-images.githubusercontent.com/69168929/183262525-0ba10b7c-f6fa-4d2a-91fd-a1f428a05b42.png)

![image](https://user-images.githubusercontent.com/69168929/183262592-58209f46-8382-4484-b968-522f782e9b53.png)

**Comment by hansfbaier** [comment]
> Did you mean to get rid of the ground plane on F.Cu?

No that was an accident. I'll put it back in.

**Comment by hansfbaier** [comment]
That is weird, the ground plane now has only tiny spaces to normal tracks,
although I already put 0.3mm clearance in the ground plane parameters:
![image](https://user-images.githubusercontent.com/148607/183355472-077b36ad-292c-46af-bed8-e37f3199598c.png)

**Comment by nikitalita** [comment]
I had noticed that too; I am not certain how to fix that.

**Comment by hansfbaier** [comment]
Looks like a bug in recent KiCAD :(
No parameters seem to influence it.

**Comment by hansfbaier** [comment]
I filed an issue at KiCAD, and posted on Twitter.
Let's see how that goes
https://gitlab.com/kicad/code/kicad/-/issues/12184
https://twitter.com/hansfbaier/status/1556534673005690882

**Comment by hansfbaier** [comment]
A kind soul on Twitter gave the right hint:
![image](https://user-images.githubusercontent.com/148607/183452184-781dcf6f-df73-4e67-85b7-23d9d3103f46.png)

**Comment by hansfbaier** [comment]
![image](https://user-images.githubusercontent.com/148607/183452270-c41087c9-e4d5-47c8-ae76-7bc3cbc38611.png)

**Comment by hansfbaier** [comment]
But it changing that didn't do anything. grr

**Comment by hansfbaier** [comment]
hmmm
![image](https://user-images.githubusercontent.com/148607/183452648-4ce911a0-d7cb-404a-b4ae-f1e50bb344d4.png)

**Comment by hansfbaier** [comment]
This one might be it:
![image](https://user-images.githubusercontent.com/148607/183453067-80785b1c-d9e0-4c8f-a7ea-592d349ddd0a.png)

**Comment by hansfbaier** [comment]
Ha! I deleted all the custom rules, then the rules set in the GUI apply.
The 'Custom rules' were probably the import from the previous version.
We have learned something!

**Comment by hansfbaier** [comment]
Now THAT looks more like it!
![image](https://user-images.githubusercontent.com/148607/183453389-4367dace-b706-43dc-9761-1a46b239c7d1.png)

**Comment by hansfbaier** [comment]
Committed interim state. Now there is a ton of DRC violations.
Homework for tomorrow.

**Comment by hansfbaier** [comment]
Ah minimum spacing should be this:
![image](https://user-images.githubusercontent.com/148607/183547847-64d16e06-8e5a-477f-8b50-173ad0b16c39.png)
Had to fix a couple of traces, now it should be fine.

**Comment by nikitalita** [comment]
Excellent, I’ll double check it

**Comment by hansfbaier** [comment]
@nikitalita I just pushed a new version, that should be good now. Still did some modifications and added some ground headers. Good for hacking/prototyping

**Comment by hansfbaier** [comment]
Should be ready to fab I hope, but it won't hurt if you check again.

**Comment by hansfbaier** [comment]
@nikitalita I just pushed the latest version.
Please pull and check again.

**Comment by hansfbaier** [comment]
The old version works well with all its weaknesses, so let's hope this one screams!

**Comment by hansfbaier** [comment]
@nikitalita BTW, these DAC boards are dirt cheap and they sound fantastic!
https://www.aliexpress.com/item/1005002898278583.html

**Comment by hansfbaier** [comment]
And they are in stock again!
![image](https://user-images.githubusercontent.com/148607/183587683-73fabfd3-4815-4855-9207-1f494452963e.png)

**Comment by hansfbaier** [comment]
and cost twice as much as the module in single quantities (gasp).

**Comment by nikitalita** [comment]
lol, I already bought like three of them for 12 bucks

**Comment by nikitalita** [comment]
The board has passed review and is in production; when I get it, I’ll let you know how it works

**Comment by hansfbaier** [comment]
@nikitalita Great! When it works I'll cut a release

**Comment by nikitalita** [comment]
I have tested the board; I know that the DAC works at least, I still have to test ADAT input and output.

I do notice a couple issues while soldering on the headers: 

- There are ground vias that are too close to the headers for the cyclone board on the USB side. This makes it very easy to accidentally bridge one of the Pins to ground during assembly. I recommend we either move or get rid of the vias that are less than 2mm from the header PTHs.
- We should specify that the cyclone board headers on the ADATiface board be female. It’s very easy to install the male headers slightly crooked on the ADATiface and it is harder to get the core board in with female sockets on it.
- we should place orientation indicators for the core board on the ADATiface board; it’s too easy to install it in reverse. Maybe something like an indicator of which direction the DC power plug goes?

**Comment by hansfbaier** [comment]
Can you post a screenshot of what vias you are talking about?
I actually use female headers on the board :] They have the same footprint anyway.
I think it would be best to just delete the silkscreen of the headers, because they have the same footprint anyway.
Orientation indicators would be a good idea.
